"""PDF report generator for Three-O platform. Supports Korean text."""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import Optional

from fpdf import FPDF


KOREAN_FONT_PATHS = [
    "/System/Library/Fonts/Supplemental/AppleGothic.ttf",
    "/System/Library/Fonts/AppleSDGothicNeo.ttc",
    "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",
    "/usr/share/fonts/nanum-gothic/NanumGothic.ttf",
]

COLORS = {
    "primary": (41, 98, 255),
    "secondary": (100, 116, 139),
    "success": (34, 197, 94),
    "warning": (245, 158, 11),
    "danger": (239, 68, 68),
    "text": (30, 41, 59),
    "light_bg": (248, 250, 252),
    "border": (226, 232, 240),
}

SEVERITY_COLORS = {
    "critical": COLORS["danger"],
    "high": (220, 38, 38),
    "medium": COLORS["warning"],
    "warning": COLORS["warning"],
    "low": COLORS["secondary"],
    "info": (59, 130, 246),
}


class ThreeOPDF(FPDF):
    """Custom PDF class for Three-O reports."""

    def __init__(self, brand: str = ""):
        super().__init__()
        self.brand = brand
        self._setup_fonts()

    def _setup_fonts(self):
        """Register Korean font if available."""
        self.korean_available = False
        for font_path in KOREAN_FONT_PATHS:
            if os.path.exists(font_path):
                try:
                    self.add_font("Korean", "", font_path, uni=True)
                    self.add_font("Korean", "B", font_path, uni=True)
                    self.korean_available = True
                    break
                except Exception:
                    continue

    def _set_font(self, style="", size=10):
        """Set font with Korean fallback."""
        if self.korean_available:
            self.set_font("Korean", style, size)
        else:
            self.set_font("Helvetica", style, size)

    def header(self):
        self._set_font("B", 9)
        self.set_text_color(*COLORS["secondary"])
        self.cell(0, 8, f"Three-O Audit Report | {self.brand}", 0, 0, "L")
        self.cell(0, 8, datetime.now().strftime("%Y-%m-%d"), 0, 1, "R")
        self.set_draw_color(*COLORS["border"])
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self._set_font("", 8)
        self.set_text_color(*COLORS["secondary"])
        self.cell(0, 10, f"Generated by Three-O v1.0.0 | Page {self.page_no()}/{{nb}}", 0, 0, "C")

    def add_title_page(self, data: dict):
        """Add branded title page."""
        self.add_page()
        self.ln(40)

        self._set_font("B", 28)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 15, "Three-O", 0, 1, "C")

        self._set_font("", 14)
        self.set_text_color(*COLORS["secondary"])
        self.cell(0, 10, "SEO + GEO + AAO Unified Optimization Report", 0, 1, "C")

        self.ln(20)
        self._set_font("B", 22)
        self.set_text_color(*COLORS["text"])
        self.cell(0, 12, self.brand, 0, 1, "C")

        self.ln(15)
        score = data.get("three_o_score", {})
        score_val = score.get("score", 0)
        grade = score.get("grade", "N/A")

        self._draw_score_circle(score_val, grade)

        self.ln(20)
        self._set_font("", 11)
        self.set_text_color(*COLORS["secondary"])
        self.cell(0, 8, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, "C")
        self.cell(0, 8, "Powered by JaeHyunGround Three-O Platform", 0, 1, "C")

    def _draw_score_circle(self, score: float, grade: str):
        """Draw the main score display."""
        self._set_font("B", 48)
        if score >= 70:
            self.set_text_color(*COLORS["success"])
        elif score >= 50:
            self.set_text_color(*COLORS["warning"])
        else:
            self.set_text_color(*COLORS["danger"])
        self.cell(0, 25, f"{score:.1f}", 0, 1, "C")

        self._set_font("B", 18)
        self.cell(0, 10, f"/ 100  ({grade})", 0, 1, "C")

    def add_executive_summary(self, data: dict):
        """Add executive summary page."""
        self.add_page()
        self._section_title("Executive Summary")

        score = data.get("three_o_score", {})
        pillars = score.get("pillars", {})

        if pillars:
            self._set_font("B", 11)
            self.set_text_color(*COLORS["text"])
            self.cell(0, 10, "Pillar Scores", 0, 1)

            for pillar_name, pillar_data in pillars.items():
                p_score = pillar_data.get("score", 0) if isinstance(pillar_data, dict) else pillar_data
                self._draw_score_bar(pillar_name.upper(), float(p_score))

        self.ln(10)
        top_issues = data.get("top_issues", [])
        if top_issues:
            self._set_font("B", 11)
            self.set_text_color(*COLORS["text"])
            self.cell(0, 10, "Top Priority Actions", 0, 1)

            for i, issue in enumerate(top_issues[:5], 1):
                severity = issue.get("severity", "medium")
                color = SEVERITY_COLORS.get(severity, COLORS["secondary"])
                self._set_font("B", 9)
                self.set_text_color(*color)
                self.cell(8, 7, f"{i}.", 0, 0)
                self.set_fill_color(*color)
                self.cell(18, 7, severity.upper(), 0, 0, "C", fill=True)
                self.set_text_color(*COLORS["text"])
                self._set_font("", 9)
                self.cell(0, 7, f"  {issue.get('message', '')}", 0, 1)

    def add_pillar_section(self, pillar: str, data: dict):
        """Add a pillar analysis section."""
        pillar_data = data.get(pillar, {})
        if not pillar_data:
            return

        self.add_page()
        pillar_titles = {"seo": "SEO Analysis", "geo": "GEO Analysis", "aao": "AAO Analysis"}
        self._section_title(pillar_titles.get(pillar, pillar.upper()))

        p_score = pillar_data.get("score", 0)
        self._set_font("B", 14)
        self.set_text_color(*COLORS["text"])
        self.cell(0, 10, f"Score: {p_score}/100", 0, 1)
        self.ln(5)

        dimensions = pillar_data.get("dimensions", {})
        if dimensions:
            self._set_font("B", 10)
            self.cell(0, 8, "Dimension Breakdown", 0, 1)
            self.ln(3)

            for dim_name, dim_val in dimensions.items():
                score_val = dim_val if isinstance(dim_val, (int, float)) else dim_val.get("score", 0)
                label = dim_name.replace("_", " ").title()
                self._draw_score_bar(label, float(score_val))

        self.ln(8)
        issues = pillar_data.get("issues", [])
        if issues:
            self._set_font("B", 10)
            self.set_text_color(*COLORS["text"])
            self.cell(0, 8, f"Issues ({len(issues)})", 0, 1)
            self.ln(2)

            for issue in issues[:10]:
                severity = issue.get("severity", "info")
                color = SEVERITY_COLORS.get(severity, COLORS["secondary"])
                self._set_font("", 9)
                self.set_text_color(*color)
                self.cell(5, 6, "", 0, 0)
                self.set_fill_color(*color)
                self.cell(16, 6, severity.upper(), 0, 0, "C", fill=True)
                self.set_text_color(*COLORS["text"])
                self.cell(0, 6, f"  {issue.get('message', '')}", 0, 1)

    def add_action_plan(self, data: dict):
        """Add action plan page."""
        self.add_page()
        self._section_title("Action Plan")

        all_issues = []
        for pillar in ["seo", "geo", "aao"]:
            for issue in data.get(pillar, {}).get("issues", []):
                all_issues.append({"pillar": pillar.upper(), **issue})

        severity_order = {"critical": 0, "high": 1, "medium": 2, "warning": 3, "low": 4}
        all_issues.sort(key=lambda x: severity_order.get(x.get("severity", "low"), 5))

        col_widths = [15, 18, 20, 120]
        headers = ["#", "Priority", "Area", "Action"]
        self._set_font("B", 9)
        self.set_fill_color(*COLORS["light_bg"])
        for i, (header, w) in enumerate(zip(headers, col_widths)):
            self.cell(w, 7, header, 1, 0, "C", fill=True)
        self.ln()

        self._set_font("", 8)
        for i, issue in enumerate(all_issues[:20], 1):
            severity = issue.get("severity", "low")
            priority = "P0" if severity == "critical" else "P1" if severity == "high" else "P2"

            self.set_text_color(*COLORS["text"])
            self.cell(col_widths[0], 6, str(i), 1, 0, "C")
            color = SEVERITY_COLORS.get(severity, COLORS["secondary"])
            self.set_text_color(*color)
            self.cell(col_widths[1], 6, priority, 1, 0, "C")
            self.set_text_color(*COLORS["text"])
            self.cell(col_widths[2], 6, issue.get("pillar", ""), 1, 0, "C")
            msg = issue.get("message", "")[:65]
            self.cell(col_widths[3], 6, msg, 1, 0, "L")
            self.ln()

    def _section_title(self, title: str):
        """Draw section title."""
        self._set_font("B", 16)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 12, title, 0, 1)
        self.set_draw_color(*COLORS["primary"])
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(8)

    def _draw_score_bar(self, label: str, score: float):
        """Draw a horizontal score bar."""
        self._set_font("", 9)
        self.set_text_color(*COLORS["text"])
        self.cell(50, 7, label, 0, 0)

        bar_x = self.get_x()
        bar_y = self.get_y() + 1.5
        bar_width = 80
        bar_height = 4

        self.set_fill_color(*COLORS["border"])
        self.rect(bar_x, bar_y, bar_width, bar_height, "F")

        if score >= 70:
            fill_color = COLORS["success"]
        elif score >= 50:
            fill_color = COLORS["warning"]
        else:
            fill_color = COLORS["danger"]

        fill_width = bar_width * (score / 100)
        self.set_fill_color(*fill_color)
        self.rect(bar_x, bar_y, fill_width, bar_height, "F")

        self.set_x(bar_x + bar_width + 3)
        self._set_font("B", 9)
        self.cell(20, 7, f"{score:.0f}", 0, 1)


def generate_pdf_report(data: dict, output_path: Optional[str] = None) -> str:
    """Generate PDF report from audit data."""
    brand = data.get("brand", "Unknown")

    pdf = ThreeOPDF(brand)
    pdf.alias_nb_pages()

    pdf.add_title_page(data)
    pdf.add_executive_summary(data)

    for pillar in ["seo", "geo", "aao"]:
        if data.get(pillar):
            pdf.add_pillar_section(pillar, data)

    pdf.add_action_plan(data)

    if not output_path:
        reports_dir = os.path.join(os.getcwd(), "reports")
        os.makedirs(reports_dir, exist_ok=True)
        date_str = datetime.now().strftime("%Y%m%d")
        output_path = os.path.join(reports_dir, f"{brand}-{date_str}-full.pdf")

    pdf.output(output_path)
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Three-O PDF report generator")
    parser.add_argument("--input", required=True, help="Audit data JSON file")
    parser.add_argument("--output", help="Output PDF path")
    parser.add_argument("--brand", help="Brand name override")
    args = parser.parse_args()

    from pathlib import Path
    data = json.loads(Path(args.input).read_text())

    if args.brand:
        data["brand"] = args.brand

    output_path = generate_pdf_report(data, args.output)
    print(f"PDF report saved: {output_path}")


if __name__ == "__main__":
    main()
