"""Report generation for Three-O platform. Outputs PDF, Markdown, or JSON."""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


def get_reports_dir() -> Path:
    reports = Path.cwd() / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    return reports


def generate_markdown_report(data: dict) -> str:
    """Generate Markdown report from audit data."""
    brand = data.get("brand", "Unknown")
    date = datetime.now().strftime("%Y-%m-%d")
    score = data.get("three_o_score", 0)
    grade = data.get("grade", "N/A")

    sections = [
        f"# Three-O Audit Report: {brand}",
        f"Date: {date}",
        "",
        "## Executive Summary",
        "",
        f"**Three-O Score: {score}/100** ({grade})",
        "",
        "| Pillar | Score | Weight |",
        "|--------|-------|--------|",
    ]

    pillars = data.get("pillars", {})
    weights = data.get("weights_applied", {})
    for pillar in ["seo", "geo", "aao"]:
        s = pillars.get(pillar, 0)
        w = weights.get(pillar, 0)
        sections.append(f"| {pillar.upper()} | {s}/100 | {w:.1%} |")

    sections.append("")
    sections.append("## Key Findings")
    sections.append("")
    for i, finding in enumerate(data.get("findings", [])[:10], 1):
        severity = finding.get("severity", "info")
        desc = finding.get("description", "")
        sections.append(f"{i}. **[{severity.upper()}]** {desc}")

    sections.append("")
    sections.append("## Action Plan")
    sections.append("")
    for i, action in enumerate(data.get("actions", [])[:10], 1):
        impact = action.get("impact", "")
        desc = action.get("description", "")
        sections.append(f"{i}. {desc} — Expected impact: {impact}")

    sections.append("")
    sections.append("---")
    sections.append(f"Generated by Three-O Platform v1.0 on {date}")

    return "\n".join(sections)


def generate_json_report(data: dict) -> str:
    """Generate JSON report from audit data."""
    report = {
        "meta": {
            "generated_at": datetime.now().isoformat(),
            "version": "1.0.0",
            "platform": "Three-O",
        },
        "scores": {
            "three_o_score": data.get("three_o_score"),
            "grade": data.get("grade"),
            "pillars": data.get("pillars", {}),
            "weights": data.get("weights_applied", {}),
        },
        "industry": data.get("industry"),
        "findings": data.get("findings", []),
        "actions": data.get("actions", []),
    }
    return json.dumps(report, indent=2, ensure_ascii=False)


def save_report(content: str, brand: str, report_type: str, fmt: str) -> Path:
    """Save report to file and return path."""
    reports_dir = get_reports_dir()
    date = datetime.now().strftime("%Y%m%d")
    filename = f"{brand}-{date}-{report_type}.{fmt}"
    filepath = reports_dir / filename
    filepath.write_text(content, encoding="utf-8")
    return filepath


def main():
    parser = argparse.ArgumentParser(description="Generate Three-O reports")
    parser.add_argument("--input", required=True, help="Input JSON data file")
    parser.add_argument("--format", choices=["md", "json", "pdf"], default="md", help="Output format")
    parser.add_argument("--type", choices=["full", "seo", "geo", "aao"], default="full", help="Report type")
    parser.add_argument("--json", action="store_true", help="Output filepath as JSON")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    data = json.loads(input_path.read_text())
    brand = data.get("brand", "unknown").replace(" ", "-").lower()

    if args.format == "md":
        content = generate_markdown_report(data)
    elif args.format == "json":
        content = generate_json_report(data)
    elif args.format == "pdf":
        print("PDF generation requires weasyprint. Use: pip install weasyprint", file=sys.stderr)
        content = generate_markdown_report(data)
        args.format = "md"

    filepath = save_report(content, brand, args.type, args.format)

    if args.json:
        print(json.dumps({"path": str(filepath), "format": args.format}))
    else:
        print(f"Report saved: {filepath}")


if __name__ == "__main__":
    main()
